const durationData = [
	{ label: '1 hour', value: '1 hour' },
	{ label: '2 hours', value: '2 hours' },
	{ label: '3 hours', value: '3 hours' },
	{ label: '4 hours', value: '4 hours' },
	{ label: '5 hours', value: '5 hours' },
	{ label: '6 hours', value: '6 hours' },
	{ label: '7 hours', value: '7 hours' },
	{ label: '8 hours', value: '8 hours' },
	{ label: '9 hours', value: '9 hours' },
	{ label: '10 hours', value: '10 hours' },
	{ label: '11 hours', value: '11 hours' },
	{ label: '12 hours', value: '12 hours' },
	{ label: '13 hours', value: '13 hours' },
	{ label: '14 hours', value: '14 hours' },
	{ label: '15 hours', value: '15 hours' },
	{ label: '16 hours', value: '16 hours' },
	{ label: '17 hours', value: '17 hours' },
	{ label: '18 hours', value: '18 hours' },
	{ label: '19 hours', value: '19 hours' },
	{ label: '20 hours', value: '20 hours' },
	{ label: '21 hours', value: '21 hours' },
	{ label: '22 hours', value: '22 hours' },
	{ label: '23 hours', value: '23 hours' },
	{ label: '24 hours', value: '24 hours' },
];

const availabilityData = [
	{ label: 'Mon', value: 'Monday' },
	{ label: 'Tue', value: 'Tuesday' },
	{ label: 'Wed', value: 'Wednesday' },
	{ label: 'Thu', value: 'Thursday' },
	{ label: 'Fri', value: 'Friday' },
	{ label: 'Sat', value: 'Saturday' },
	{ label: 'Sun', value: 'Sunday' },
];

const languagesData = [
	{ code: 'tl', name: 'Filipino' },
	{ code: 'ceb', name: 'Cebuano' },
	{ code: 'en', name: 'English' },
	{ code: 'es', name: 'Spanish' },
	{ code: 'fr', name: 'French' },
	{ code: 'de', name: 'German' },
	{ code: 'it', name: 'Italian' },
	{ code: 'ja', name: 'Japanese' },
	{ code: 'ko', name: 'Korean' },
	{ code: 'zh', name: 'Chinese' },
	{ code: 'ru', name: 'Russian' },
	{ code: 'ar', name: 'Arabic' },
	{ code: 'hi', name: 'Hindi' },
	{ code: 'pt', name: 'Portuguese' },
	{ code: 'nl', name: 'Dutch' },
	{ code: 'sv', name: 'Swedish' },
	{ code: 'da', name: 'Danish' },
	{ code: 'no', name: 'Norwegian' },
	{ code: 'fi', name: 'Finnish' },
	{ code: 'tr', name: 'Turkish' },
	{ code: 'el', name: 'Greek' },
	{ code: 'pl', name: 'Polish' },
	{ code: 'th', name: 'Thai' },
	{ code: 'cs', name: 'Czech' },
	{ code: 'hu', name: 'Hungarian' },
	{ code: 'he', name: 'Hebrew' },
	{ code: 'id', name: 'Indonesian' },
	{ code: 'ms', name: 'Malay' },
	{ code: 'vi', name: 'Vietnamese' },
];

//data for time with 30 minutes interval
const timeData = [
	{ label: '12:00 AM', value: '00:00' },
	{ label: '12:30 AM', value: '00:30' },
	{ label: '1:00 AM', value: '01:00' },
	{ label: '1:30 AM', value: '01:30' },
	{ label: '2:00 AM', value: '02:00' },
	{ label: '2:30 AM', value: '02:30' },
	{ label: '3:00 AM', value: '03:00' },
	{ label: '3:30 AM', value: '03:30' },
	{ label: '4:00 AM', value: '04:00' },
	{ label: '4:30 AM', value: '04:30' },
	{ label: '5:00 AM', value: '05:00' },
	{ label: '5:30 AM', value: '05:30' },
	{ label: '6:00 AM', value: '06:00' },
	{ label: '6:30 AM', value: '06:30' },
	{ label: '7:00 AM', value: '07:00' },
	{ label: '7:30 AM', value: '07:30' },
	{ label: '8:00 AM', value: '08:00' },
	{ label: '8:30 AM', value: '08:30' },
	{ label: '9:00 AM', value: '09:00' },
	{ label: '9:30 AM', value: '09:30' },
	{ label: '10:00 AM', value: '10:00' },
	{ label: '10:30 AM', value: '10:30' },
	{ label: '11:00 AM', value: '11:00' },
	{ label: '11:30 AM', value: '11:30' },
	{ label: '12:00 PM', value: '12:00' },
	{ label: '12:30 PM', value: '12:30' },
	{ label: '1:00 PM', value: '13:00' },
	{ label: '1:30 PM', value: '13:30' },
	{ label: '2:00 PM', value: '14:00' },
	{ label: '2:30 PM', value: '14:30' },
	{ label: '3:00 PM', value: '15:00' },
	{ label: '3:30 PM', value: '15:30' },
	{ label: '4:00 PM', value: '16:00' },
	{ label: '4:30 PM', value: '16:30' },
	{ label: '5:00 PM', value: '17:00' },
	{ label: '5:30 PM', value: '17:30' },
	{ label: '6:00 PM', value: '18:00' },
	{ label: '6:30 PM', value: '18:30' },
	{ label: '7:00 PM', value: '19:00' },
	{ label: '7:30 PM', value: '19:30' },
	{ label: '8:00 PM', value: '20:00' },
	{ label: '8:30 PM', value: '20:30' },
	{ label: '9:00 PM', value: '21:00' },
	{ label: '9:30 PM', value: '21:30' },
	{ label: '10:00 PM', value: '22:00' },
	{ label: '10:30 PM', value: '22:30' },
	{ label: '11:00 PM', value: '23:00' },
	{ label: '11:30 PM', value: '23:30' },
];

export { durationData, availabilityData, languagesData };
